name: Graem Wiki
permalink: /:title

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

ga_id: "G-LD2CNN524G"

defaults:
  -
    scope:
      path: "wiki/" # an empty string here means all files in the project
    values:
      layout: post
      
